-- Historical no-op.
--
-- This migration originally created the pgvector extension and added
-- `semantic_embedding*` columns + HNSW indexes to the v1alpha1 tables
-- backing the semantic-search feature. The feature was removed in its
-- entirety; see 008_drop_semantic_embeddings.sql for the corresponding
-- cleanup of the columns and indexes on databases that had previously
-- applied the original 003.
--
-- The file is retained so that:
--   1. Fresh installs still record a `schema_migrations` row for
--      version 203 (= 003 + the v1alpha1 VersionOffset of 200), keeping
--      the migration sequence intact and contiguous with deployments
--      that historically applied the original 003.
--   2. The bundled PostgreSQL image no longer needs pgvector binaries
--      available — the original `CREATE EXTENSION vector` is gone, so
--      a stock `postgres:18` (the Helm chart default) boots cleanly
--      without pulling in a vector-capable image.
--
-- A trailing `SELECT 1;` is included so the file parses to a real
-- statement rather than relying on PostgreSQL/pgx accepting an empty
-- query.

SELECT 1;
